controller_manager:
  ros__parameters:
    update_rate: 50

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster # Controlador para publicar o estado das juntas

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController # Controlador para robôs com tração diferencial

diff_drive_controller:
  ros__parameters:
      left_wheel_names: ["left_wheel_1_joint", "left_wheel_2_joint"]
      right_wheel_names: ["right_wheel_1_joint", "right_wheel_2_joint"]
      wheel_separation: 0.183
      wheel_radius: 0.033

      odom_frame_id: "odom"
      base_frame_id: "base_link"

      pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
      twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

      enable_odom_tf: true
      publish_rate: 50.0

      linear.x.max_velocity: 1.0
      linear.x.min_velocity: -1.0
      angular.z.max_velocity: 1.0
      angular.z.min_velocity: -1.0
      